sudo: true
dist: trusty
sudo: required
language: python
python:
  - "2.7"
before_install:
  - wget 'http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh' -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - sudo apt-get update
install:
  - conda create --yes -n mogutda-test python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - source activate mogutda-test
  - pip install -U .
script:
  - python setup.py test
